## name: CyberXero
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Cosmic-Cyberpunk-Kitten-Theme

background            #000000
foreground            #77fff9
selection_background  #77fff9
selection_foreground  #000000
cursor                #fb1010

# Black, Gray, Silver, White

color0                #000000
color8                #77fff9
color7                #fb1010
color15               #fb1010

# Red

color1                #fb1010
color9                #fb1010

# Green

color2                #77fff9
color10               #77fff9

# Yellow

color3                #fb1010
color11               #fb1010

# Blue

color4                #77fff9
color12               #77fff9

# Purple

color5                #fb1010
color13               #fb1010

# Teal

color6                #77fff9
color14               #77fff9
